#!/usr/bin/ruby

# usage:
#
# 1. set bunko as landscape
# 2. scan-bunko

# set first page (front face) bottom 
# landscape

require 'optparse'

def create_fresh_output_directory
  outdir_base = 'outdir'
  n = 1
  begin
    outdir = "#{outdir_base}#{n}"
    Dir.mkdir outdir
  rescue Errno::EEXIST
    n += 1
    retry
  end
  outdir
end

op = OptionParser.new
$opt_o = nil
op.def_option('-o DIR', '--output DIR', 'output directory') {|arg| $opt_o = arg }
op.parse(ARGV)

if $opt_o
  outdir = $opt_o
  unless File.directory? outdir
    Dir.mkdir outdir
  end
else
  outdir = create_fresh_output_directory
end

Dir.chdir outdir

nums = Dir["raw*.tiff\0out*.tiff"].reject {|f|
  /\A(raw|out)([0-9]+)\.tiff\z/ !~ f
}.map {|f| f[/\d+/].to_i }
if nums.empty?
  start = 0
else
  start = nums.max + 1
end

system(
  "scanimage",
  "--format=tiff",
  "--batch=raw%d.tiff",
  "--batch-start=#{start}",
  "--source", "ADF Duplex",
  "--mode", "Color",
  "--resolution", "300",
  "-l", "30",
  "-x", "160",
  "--ald=yes")

fs = Dir["raw*.tiff"].reject {|f| /\Araw([0-9]+)\.tiff\z/ !~ f }
fs = fs.sort_by {|f| f[/\d+/].to_i }

numdigits = fs.last[/\d+/].length
fmt = "out%0#{numdigits}d.tiff"

Dir["out*.tiff"].each {|f|
  next if /\Aout([0-9]+)\.tiff\z/ !~ f
  digits = $1
  if digits.length != numdigits
    nf = fmt % digits.to_i
    File.rename f, nf
  end
}

fs.each {|f|
  n = f[/\d+/].to_i
  of = fmt % n
  angle = n % 2 == 0 ? "-R 270" : "-R 90"
  system("tiffcrop #{angle} #{f} #{of}")
  File.delete f
}
